export const RESOURCE_CACHE_MODULE = 'RESOURCE_CACHE_MODULE';
export const RESOURCE_CACHE_DELETE = 'RESOURCE_CACHE_DELETE';
export const RESOURCE_CACHE_SAVE = 'RESOURCE_CACHE_SAVE';
export const LOAD_ALL_PERSISTENCE_DATA = 'LOAD_ALL_PERSISTENCE_DATA';